# Load necessary libraries
library(stringr)
library(tools)

# Format Sample IDs for Microhaplotyper
# Reads a three-column, comma-separated file (.csv), formats the sample IDs
# in the second column, and saves the result to a new tab-delimited file.
# The output filename is automatically generated by appending "_zpad.txt"
# to the original filename.
#
# input_file_path: The path to the input .csv file. The file should have
#                  no header. The columns should be:
#                  1. Filename (.sam format)
#                  2. Sample ID to be formatted
#                  3. Population identifier (e.g., "NA")
#
# Example Usage:
# zpad_ids(input_file_path = "my_sample_ids.csv")

zpad_ids <- function(input_file_path) {
  
  # --- 1. Generate Output Path ---
  # Automatically create the output filename by removing the original
  # extension and appending "_zpad.txt".
  base_name <- file_path_sans_ext(input_file_path)
  output_file_path <- paste0(base_name, "_zpad.txt")
  
  # --- 2. Input Validation ---
  # Check if the input file exists before proceeding.
  if (!file.exists(input_file_path)) {
    stop("Error: Input file not found at path: ", input_file_path)
  }
  
  # --- 3. Read Input Data ---
  # Read the comma-separated file (.csv). We assume no header.
  message("Reading data from: ", input_file_path)
  inds <- read.csv(input_file_path, sep = ",", header = FALSE, stringsAsFactors = FALSE)
  
  # Check if the input data has the expected three columns
  if (ncol(inds) != 3) {
    stop("Error: Input file does not have three columns. Please check the format.")
  }
  
  # Extract the column with the sample IDs (the second column, V2).
  original_ids <- inds$V2
  
  # --- 4. Format the IDs ---
  # This is the core logic for reformatting each ID.
  # We use sapply to apply this logic to every ID in the list.
  formatted_ids <- sapply(original_ids, function(id) {
    
    # Separate the numeric part from the replicate letter (e.g., 'b', 'c').
    numeric_part <- str_extract(id, "^[0-9]+")
    replicate_suffix <- str_extract(id, "[a-zA-Z]+$")
    
    # If a suffix was not found, replace NA with an empty string.
    if (is.na(replicate_suffix)) {
      replicate_suffix <- ""
    }
    
    # Check if a numeric part was found.
    if (is.na(numeric_part)) {
      warning("Could not find numeric part for ID: ", id, ". Skipping.")
      return(NA) # Return NA for IDs that don't fit the pattern
    }
    
    # Format the numeric part to be 7 digits, then prepend "z".
    padded_id <- paste0("z", sprintf("%07d", as.numeric(numeric_part)))
    
    # Combine the new padded ID with its original replicate letter.
    final_id <- paste0(padded_id, replicate_suffix)
    
    return(final_id)
  })
  
  # --- 5. Prepare and Write Output ---
  # Create a new data frame with the formatted IDs.
  output_data <- data.frame(
    filename = inds$V1,
    formatted_id = formatted_ids,
    population = inds$V3
  )
  
  # Write the resulting data frame to a tab-delimited text file.
  message("Writing formatted data to: ", output_file_path)
  write.table(
    output_data,
    output_file_path,
    sep = "\t",
    col.names = FALSE,
    row.names = FALSE,
    quote = FALSE
  )
  
  message("Processing complete.")
}